from pydantic import BaseModel, Field

class PrediccionPeticion(BaseModel):
    estado_civil: int = Field(default=1, ge=1, le=6, description='Estado Civil (1-6)')
    modo_aplicacion: int = Field(default=1, ge=1, le=50, description='Modo de aplicación')
    orden_aplicacion: int = Field(default=1, ge=0, le=9, description='Orden de aplicación (0-9)')
    curso: int = Field(default=1, ge=1, le=10000, description='Curso inscrito')
    asistencia_diurna_nocturna: int = Field(default=1, ge=0, le=1, description='Asistencia diurna/nocturna (0 o 1)')
    calificacion_previa: int = Field(default=1, ge=1, le=50, description='Calificación previa')
    nota_admision: float = Field(default=120.0, ge=0.0, le=200.0, description='Nota de admisión (0-200)')
    desplazado: int = Field(default=0, ge=0, le=1, description='Estudiante desplazado (0 o 1)')
    necesidades_educativas_especiales: int = Field(default=0, ge=0, le=1, description='Necesidades educativas especiales (0 o 1)')
    deudor: int = Field(default=0, ge=0, le=1, description='Deudor financiero (0 o 1)')
    mensualidades_al_dia: int = Field(default=1, ge=0, le=1, description='Mensualidades al día (0 o 1)')
    genero: int = Field(default=0, ge=0, le=1, description='Género (0 o 1)')
    becario: int = Field(default=0, ge=0, le=1, description='Es becario (0 o 1)')
    edad_al_matricularse: int = Field(default=20, ge=15, le=100, description='Edad al matricularse (15-100)')
    unidades_curriculares_1er_sem_inscritas: int = Field(default=5, ge=0, le=30, description='Unidades curriculares inscritas en el 1er semestre')
    unidades_curriculares_1er_sem_evaluaciones: int = Field(default=5, ge=0, le=40, description='Evaluaciones cursadas en el 1er semestre')
    unidades_curriculares_1er_sem_aprobadas: int = Field(default=5, ge=0, le=30, description='Unidades curriculares aprobadas en el 1er semestre')
    unidades_curriculares_1er_sem_nota: float = Field(default=13.0, ge=0.0, le=20.0, description='Nota promedio en el 1er semestre (0-20)')
