name: Despliegue en Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Desplegar Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Desplegar en Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
